apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kubernetes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-kubernetes
  template:
    metadata:
      labels:
        app: docker-kubernetes
    spec:
      containers:
        - name: spring-app
          # FORMAT: <your-dockerhub-username>/<repo-name>:<tag>
          image: tejait/docker-kubernetes:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
# Service remains the same as before
apiVersion: v1
kind: Service
metadata:
  name: docker-kubernetes-service
spec:
  type: NodePort
  selector:
    app: docker-kubernetes
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001